### ISSUE TITLE
Receive QR code is missing brandmark overlay

### ISSUE THREAD

**Issue by ElijahCouchOrangeme** [CalebCouch/orangeme#4]
Inside the receive page the logo is overlaying the QR code causing a ugly and non reliable QR code

**Comment by dav-anderson** [comment]
This has been temporarily removed, renaming this issue to better reflect the new issue

**Comment by Elicouch** [comment]
Fixed QR code so the brandmark is not overlaying qr code

**Comment by ElijahCouchOrangeme** [comment]
https://github.com/CalebCouch/orangeme/pull/35
