### ISSUE TITLE
Bitcoin address back arrow error

### ISSUE THREAD

**Issue by EllaCouch20** [CalebCouch/orangeme#71]
After scanning a bitcoin address, pressing the back arrow clears the input field. Requires you to press the back arrow a second time to back out of the page.

**Comment by bradstevens1** [comment]
Hello @EllaCouch20 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[Bitcoin live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Etandooley** [comment]
Hello @EllaCouch20  You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[bitcoin live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent
